### ISSUE TITLE
TypeError: function got multiple values for argument 'register'

### ISSUE THREAD

**Issue by capaulson** [deshipu/micropython-bno055#3]
I'm using MicroPython v1.9.4-518-g9fb1f18cf. I get the following error: 

```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
  File "bno055.py", line 46, in __init__
  File "bno055.py", line 91, in init
  File "bno055.py", line 101, in reset
  File "functools.py", line 5, in _partial
TypeError: function got multiple values for argument 'register'
```

Any thoughts?

**Comment by deshipu** [comment]
No idea. Possibly they broke something in MicroPython again.

**Comment by capaulson** [comment]
Is there anyway you could quickly check what version of micropython you were using when this worked?

**Comment by FarmerMark** [comment]
Hey deshipu - I'm having the same error as capaulson. I've tried with micropython esp32 firemware v1.9.4 and 1.10 - same issue. 

I don't quite understand what the function partial() is doing. 

Here's the traceback:

_>>> exec(open('./main.py').read(),globals())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 7, in <module>
  File "bno055.py", line 44, in __init__
  File "bno055.py", line 89, in init
  File "bno055.py", line 99, in reset
  File "functools.py", line 5, in _partial
TypeError: function got multiple values for argument 'register'_

I'm using the same code in main.py from your bno055.py sample.

it seems to be having a problem when calling operation_mode() from reset().

It appears operation_mode() is a function returned by a call to partial():

_operation_mode = partial(_register, register=0x3d)_

No idea why it's generating this error.

**Comment by deshipu** [comment]
I really can't help. Changes like these are the reason why I've given up on MicroPython on moved on. You might get some help on the forums.

**Comment by ghost** [comment]
We ran into the same problem, and ultimately got it working by running the I2C bus at 15kHz (!).

I do not think it's MicroPython. The BNO055 has some very tight timing issues, and the ESP32 cannot handle that. Works fine with other microcontrollers, eg. nrf52840. So before giving up on Micropython, you may look into using another controller. 

P.S. We are using the Adafruit CircuitPython driver, but hopefully "going slooow" works with this driver also.

**Comment by deshipu** [comment]
The CircuitPython driver is written differently and doesn't stumble into this particular problem. I'm quite sure this is a bug in MicroPython and the way that it now handles closures and function signatures. I have no desire to try and fix it or work around it, because I know that if I do, in a moment there will be another breaking change, and another, and so on. I have better things to do.
